### PR TITLE
Add the Mac Roman Encoding

### PR DESCRIPTION
**Pull request by markcatley**
Source: https://en.wikipedia.org/wiki/Mac_OS_Roman

### CODE REVIEW

**Comment by markcatley** [comment]
@s3bk thanks for your help with my other PDF issues and PRs! Any thoughts on this one?

**Review by s3bk — APPROVED** [review]

**Comment by s3bk** [comment]
Looks good.
Do you think there will be more encodings added?
(also please consider joining on zulip)

**Comment by markcatley** [comment]
I had a look to try and tell what would be needed based on the Encoding enum in PDF. I couldn't see anything obvious. IdentityH didn't have a char map but I couldn't immediately understand what would be needed. Possibly should do a quick skim of the spec and see if anything jumps out.
None of the PDFs in my downloads folder had another encoding in its fonts.

**Comment by s3bk** [comment]
Then it is probably fine without a non-exhaustive marker and I will just do another breaking release.

**Pull request merged**
